privatebet/states.c

Adding block synchronization, minRaise, toCall

Adding block synchronization, minRaise, toCall 

---

privatebet/bet.c
privatebet/client.c
privatebet/common.h
privatebet/host.c
privatebet/payment.c
privatebet/states.c

Fixed: All-in keeps the game going #47

Fixed: All-in keeps the game going #47

---

privatebet/host.c
privatebet/payment.c

Fixed: Players show the cards after a fold #55
Created tag: v0.1.1

Fixed: Players show the cards after a fold #55

---

privatebet/client.c
privatebet/states.c

All-in does not progress when one player has chips chips-blockchain/pangea-poker#50 has been fixed

Made changes to fix  chips-blockchain/pangea-poker#50

---

README.md
privatebet/states.c

Made changes to README to build the libwebsockets with SSL support, and fixed the open issues

Made changes to README and fixed the open issues

---

privatebet/client.c
privatebet/common.h
privatebet/host.c
privatebet/host.h

For example if the `player at position 0` joined the table then the JSON information such as 
`{
method: "joinInfo", 
playerid: 0
}`
is pushed to the GUI for the players.

Pushing the player joinInfo to the GUI

---

privatebet/.clang-format
privatebet/bet.c
privatebet/bet.h
privatebet/cards777.c
privatebet/cards777.h
privatebet/client.c
privatebet/client.h
privatebet/commands.c
privatebet/commands.h
privatebet/common.h
privatebet/gfshare.c
privatebet/gfshare.h
privatebet/host.c
privatebet/host.h
privatebet/network.c
privatebet/network.h
privatebet/payment.c
privatebet/payment.h
privatebet/poker.c
privatebet/states.c
privatebet/states.h
privatebet/table.c
privatebet/table.h
privatebet/test.c

Copied the `.clamg-format` from `https://github.com/torvalds/linux/blob/master/.clang-format` to make the repo inconsistent with the linux coding guidelines. Which makes the repo more readable and easy to maintain.

Making coding guidelines of the repo in compliance with linux coding style

---

privatebet/bet.c
privatebet/bet.h
privatebet/cashier.c
privatebet/cashier.h
privatebet/host.c
privatebet/network.c
privatebet/network.h

The playing node looks for the actively available cashier nodes and choose one which the player trust as a cashier.

Functionalities needed to implement the cashier protocol has been added.

---

heartbeat_protocol.md
privatebet/bet.c
privatebet/commands.c
privatebet/host.c

Described how heartbeat protocol works along with the message formats in `heartbeat_protocol.md`.

Adding documentation and implementation for the heartbeat protocol

---

privatebet/bet.c
privatebet/cashier.c
privatebet/commands.c
privatebet/host.c

Cashier protocol is integrated, so now deposit and withdrawl of funds will happen through notary nodes.

Integration of cashier protocol

---

privatebet/bet.c
privatebet/client.c
privatebet/commands.c
privatebet/host.c

Dynamically computing the legacy_m_of_n_msig_addr where m is 2, and the players fund to this address at the start of the table.

Dealer now computes the msig address based on the availability of notaries

---

privatebet/bet.c
privatebet/bet.h
privatebet/cashier.c
privatebet/client.c
privatebet/commands.c
privatebet/host.c
privatebet/host.h

Make changes to push the seats_info when the player connects to the backend.

Make changes to push the seats_info when the player connects to the BE

---

privatebet/client.c

Adding BE status to walletInfo as a temporery fix to update the BE status to the GUI

Adding BE status to walletInfo as a temporery fix 

---

privatebet/bet.c
privatebet/cashier.c
privatebet/client.c
privatebet/client.h
privatebet/commands.c
privatebet/commands.h
privatebet/host.c
privatebet/host.h
privatebet/storage.c

The following issues have been fixed with these changes.
1.  Made changes to fix GUI freeze.
2.  Made couple of changes to fix the crashes, Made changes to handle read and write communications to the GUI with two different sockets one is read and other is to write.

Made changes to fix multiple issues.

---

compile.md

=== configuring in src/secp256k1 (/home/pi/libwally-core/src/secp256k1)
configure: WARNING: no configuration information is in src/secp256k1

update error fix

---

privatebet/Makefile
privatebet/bet.c
privatebet/bet.h
privatebet/client.c
privatebet/heartbeat.c
privatebet/heartbeat.h
privatebet/host.c

Implemented the heartbeat protocol which periodically checks the players active status and publish this info to the players.

Handling player disconnections - updating status to GUI

---

privatebet/Makefile
privatebet/bet.c
privatebet/bet.h
privatebet/cashier.c
privatebet/client.c
privatebet/heartbeat.c
privatebet/heartbeat.h
privatebet/host.c
privatebet/storage.c

Implemented the heartbeat protocol which periodically checks the players active status and publish this info to the players.

Handling player disconnections

---

privatebet/bet.c
privatebet/client.c
privatebet/commands.c

In the current implementation, a player can opt to sitout and rejoin and the same time a new player can join the table.

Implementing player sitout

---

.gitmodules
external/Makefile
privatebet/Makefile
privatebet/bet.c
privatebet/bet.h
privatebet/cards777.c
privatebet/cashier.c
privatebet/client.c
privatebet/commands.c
privatebet/config.c
privatebet/gfshare.c
privatebet/heartbeat.c
privatebet/host.c
privatebet/network.c
privatebet/payment.c
privatebet/states.c
privatebet/storage.c

implement https://github.com/nyorain/dlg (libdlg) library,
setup for builds system;
implement basic call subset.

add debug logging

---

privatebet/bet.c
privatebet/cashier.c
privatebet/client.c
privatebet/common.h
privatebet/config.c
privatebet/config/player_config.ini
privatebet/host.c
privatebet/host.h

As mentioned in the git issue https://github.com/chips-blockchain/bet/issues/312, the support to customize the names for the players has been added in the backend.

Adding support to the customized names

---

privatebet/bet.h
privatebet/cashier.c
privatebet/client.c
privatebet/commands.c
privatebet/common.h
privatebet/config.c
privatebet/config/dealer_config.ini
privatebet/config/player_config.ini
privatebet/err.c
privatebet/err.h
privatebet/host.c
privatebet/payment.c
privatebet/states.c

With these changes, players can configure min, max stakes of the table and player can join the table with any amount of stake b/w [min, max].
The following issues are also been fixed.
1. Game stuck at stake. https://github.com/chips-blockchain/bet/issues/318
2. -ve player balances after rejoining. https://github.com/chips-blockchain/bet/issues/310

Fixing multiple issues

---

.github/workflows/bet-cd.yml

Making changes to git workflow so that it takes the current branch latest commit while compiling

Making changes to git workflow

---

privatebet/config/cashier_config.ini

I'm removing the cashier nodes which are no longer available and also updating the keys to the few existing cashier nodes.

Updating the cashier node pubkeys

---

README.md
docs/verus_migration/ids_keys_data.md
docs/verus_migration/verus_migration.md
privatebet/Makefile
privatebet/bet.c
privatebet/bet_version.h
privatebet/client.c
privatebet/commands.c
privatebet/config/blockchain_config.ini
privatebet/host.c
privatebet/poker.c
privatebet/storage.c
privatebet/vdxf.c
privatebet/vdxf.h

1. When the cashier node gets started it is able to update the cashier IP;s at `cashiers.poker.chips10sec`.

Verus Migration - WIP

---

privatebet/bet.c
privatebet/bet.h
privatebet/bet_version.h
privatebet/config.c
privatebet/config/verus_dealer.ini
privatebet/vdxf.c
privatebet/vdxf.h

Tasks accomplished.
1. Added support to extract id info based on key.
2. Made changes to player join.

Virus Migration - WIP

---

docs/verus_migration/game_state.md
docs/verus_migration/print.md
docs/verus_migration/schema.md
privatebet/vdxf.c
privatebet/vdxf.h

Verus Migration WIP

---

privatebet/bet.c
privatebet/config.c
privatebet/help.c
privatebet/vdxf.c
privatebet/vdxf.h

The following APIs has been added.
1. list_dealers
2. list_tables
3. reset_id
4. help section for these commands.

Added few poker, verus related APIs to bet

---

privatebet/bet.c
privatebet/bet.h
privatebet/client.c
privatebet/config.c
privatebet/config/verus_player.ini
privatebet/dealer.c
privatebet/err.c
privatebet/err.h
privatebet/host.c
privatebet/player.c
privatebet/poker.c
privatebet/print.c
privatebet/print.h
privatebet/storage.c
privatebet/vdxf.c
privatebet/vdxf.h

Defined the keys for player ID and updated the deck at player ID.

Updating player deck at player IDs
